import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components';
import { Button, Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="mint" grayColor="gray" panelBackground="solid" scaling="100%" radius="full">
          {children}
        </Theme>
      </body>
    </html>
  );
}
